惑星情報管理アプリ課題のPlanetモデル作成
sayaka310/planet_app pull request #1
Opened 2021-09-21 22:01 UTC by sayaka310

お疲れ様で御座います。
ご確認をお願いいたします。

2021-09-21 22:33 UTC, kazu-taka requested changes
@sayaka310 
コメントしたので修正お願いします:bow:

2021-09-21 22:33 UTC, kazu-taka commented on database/migrations/2021_09_19_091342_create_planets_table.php
> +            $table->string('englishname');
@sayaka310 
複数の単語のときはスネークケースになるので、`english_name`に修正お願いします！

2021-09-21 22:33 UTC, kazu-taka commented on database/migrations/2021_09_19_091342_create_planets_table.php
> +            $table->string('englishname');
関連する部分も全て`english_name`に修正して下さい🙏

2021-09-21 23:22 UTC, sayaka310 commented on database/migrations/2021_09_19_091342_create_planets_table.php
> +            $table->string('englishname');
有難う御座います。
勉強になります。

2021-09-22 00:08 UTC, kazu-taka commented
@sayaka310 
問題ないのでマージしてOKです！！
![LGTM](https://image.lgtmoon.dev/141177)

2021-09-22 00:42 UTC, merged